covers_to_cbs = {
    'Pittsburgh': 'PIT',
    'Kansas City': 'KC',
    'Atlanta': 'ATL',
    'N.Y. Jets': 'NYJ',
    'Carolina': 'CAR',
    'Jacksonville': 'JAC',
    'Indianapolis': 'IND',
    'New Orleans': 'NO',
    'L.A. Chargers': 'LAC',
    'N.Y. Giants': 'NYG',
    'Seattle': 'SEA',
    'Tampa Bay': 'TB',
    'Philadelphia': 'PHI',
    'Arizona': 'ARI',
    'Baltimore': 'BAL',
    'Oakland': 'OAK',
    'Washington': 'WAS',
    'New England': 'NE',
    'Buffalo': 'BUF',
    'Chicago': 'CHI',
    'Clevelend': 'CLE',
    'San Francisco': 'SF',
    'Houston': 'HOU',
    'Miami': 'MIA',
    'Detroit': 'DET',
    'Cincinnati': 'CIN',
    'Green Bay': 'GB',
    'Dallas': 'DAL',
    'Tennessee': 'TEN',
    'Denver': 'DEN',
    'Minnesota': 'MIN',
    'L.A. Rams': 'LAR',
}
